export const ADMIN_PANEL_ROUTE = '/admin'
export const AUTHORIZATION_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ONLINE_STORE_ROUTE = '/'
export const DEVICE_ROUTE = '/device'